<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Donation Information</title>
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        form {
            margin-bottom: 20px;
        }
        label {
            display: block;
            margin: 5px 0;
        }
        input, select {
            width: 100%;
            padding: 8px;
            margin: 5px 0;
            border: 1px solid #ddd;
        }
        button {
            padding: 10px 15px;
            background-color: #4CAF50;
            color: white;
            border: none;
            cursor: pointer;
        }
        button:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>
    <h1>Donation Information</h1>

    <form id="donation-form">
        <h2>Add Donation</h2>
        <label for="donorName">Donor Name:</label>
        <input type="text" id="donorName" name="donorName" required>

        <label for="amount">Amount:</label>
        <input type="number" id="amount" name="amount" required>

        <label for="campaignId">Campaign ID:</label>
        <input type="number" id="campaignId" name="campaignId" required>

        <label for="date">Donation Date:</label>
        <input type="date" id="date" name="date" required>

        <button type="submit">Submit Donation</button>
    </form>

    <table id="donations-table">
        <thead>
            <tr>
                <th>Donation ID</th>
                <th>Donor Name</th>
                <th>Amount</th>
                <th>Campaign ID</th>
                <th>Donation Date</th>
            </tr>
        </thead>

        <tbody id="donations-tbody">
            <!-- Rows will be dynamically added here -->
        </tbody>
    </table>

    <script>
        // Placeholder for JavaScript to handle form submission and table population
        document.getElementById('donation-form').addEventListener('submit', function(event) {
            event.preventDefault(); // Prevent form submission

            // Gather form data
            const donorName = document.getElementById('donorName').value;
            const amount = document.getElementById('amount').value;
            const campaignId = document.getElementById('campaignId').value;
            const date = document.getElementById('date').value;

            // Create a new table row
            const newRow = document.createElement('tr');
            newRow.innerHTML = `
                <td><!-- Donation ID will be generated by backend --></td>
                <td>${donorName}</td>
                <td>${amount}</td>
                <td>${campaignId}</td>
                <td>${date}</td>
            `;

            // Append the new row to the donations table
            document.getElementById('donations-tbody').appendChild(newRow);

            // Reset the form
            document.getElementById('donation-form').reset();
        });
    </script>
</body>
</html>