<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Donation Page</title>
</head>
<body>
    <center>
        <h1>Donation Page</h1>
        <form id="paymentForm" action="/PaymentModule/OrderCreation" method="GET" >
            <h3>Enter Your Name</h3>
            <input name="name" id="name" type="text" required>
            <h3>Enter Amount</h3>
            <input name="amount" id="amount" type="text" required></br>
            <br>
            <button id="rzp-button1" type="button">Pay with Razorpay</button>
        </form>
    </center>

        <!-- Razorpay Checkout script -->
    <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
    <script>
        var rzp1;

        // Function to create the order ID
        function CreateOrderId() {
            var xhttp = new XMLHttpRequest();
            var name = document.getElementById('name').value;
            var amount = document.getElementById('amount').value;

            // Ensure name and amount are provided
            if (!name || !amount) {
                alert("Please enter both your name and amount.");
                return;
            }

            // Prepare the data for sending
            var data = "name=" + encodeURIComponent(name) + "&amount=" + encodeURIComponent(amount);
            console.log("Name: " + name);
			console.log("Amount: " + amount);
            // Use async request to call your backend servlet to generate order ID
            var data = "name=" + encodeURIComponent(name) + "&amount=" + encodeURIComponent(amount);
			xhttp.open("GET", "/PaymentModule/OrderCreation?" + data, true);
            xhttp.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
			
			xhttp.send(data);

            xhttp.onreadystatechange = function() {
                if (this.readyState === 4 && this.status === 200) {
                    // Fetch Razorpay order ID from the response
                    var RazorpayOrderId = this.responseText.trim();
                    console.log("Order ID: " + RazorpayOrderId);

                    // Now open Razorpay checkout
                    OpenCheckout(RazorpayOrderId);
                }
            };
        }

        // Function to open the Razorpay checkout
        function OpenCheckout(orderId) {
            var options = {
                "key": "secret_key",  // Enter your test key here
                "amount": document.getElementById('amount').value * 100,  // Amount is in paise
                "currency": "INR",
                "name": document.getElementById('name').value,  // User's name
                "description": "Donation Transaction",
                "order_id": orderId,  // The order ID generated by Razorpay
                "handler": function (response){
                    alert("Payment successful!");
                    alert("Payment ID: " + response.razorpay_payment_id);
                    alert("Order ID: " + response.razorpay_order_id);
					alert(response.razorpay_signature)
                },
                "prefill": {
                    "name": document.getElementById('name').value,
                    "email": "customer@example.com",  // Prefill email for testing
                    "contact": "9999999999"  // Prefill phone number for testing
                },
                "theme": {
                    "color": "#3399cc"
                }
            };

            rzp1 = new Razorpay(options);

            // Open Razorpay modal
            rzp1.open();
        }

        // Bind the button click to generate order ID and open Razorpay checkout
        document.getElementById('rzp-button1').onclick = function(e) {
            e.preventDefault();
            CreateOrderId();  // First generate the order ID before opening checkout
        };
    </script>
</body>
</html>
